### ISSUE TITLE
keybinds not working

### ISSUE THREAD

**Issue by underscorephil** [void-rs/void#11]
Howdy!

Neat project. Ive been giving it a go and have run into a snag with the custom keybinds.

Ive set the env var and pointed it to the default.keys found in this repo. It errors out with the below until I remove he lines for `undo_delete` and `help`:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("invalid config at line 30: undo_delete:C-z") }) }', src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Removing those gets it to launch, but the app still responds to the default bindings and does not appear to notice any changes I make.

Have you run into this before?

**Comment by zoidbergwill** [comment]
Experiencing the same issue. With an empty config file or the default one.

**Comment by alok** [comment]
I have the same issue.
