### ISSUE TITLE
Allow configuring default browser

### ISSUE THREAD

**Issue by ergl** [void-rs/void#32]
When an entry is a url starting with `http`, pressing `C-k` will try to spawn a ["firefox" process](https://github.com/void-rs/void/blob/f0a9f72ea438e593ddcaa4d5981a51941b5882a6/src/screen.rs#L554-L560), that will probably fail if you don't have your browser configured like that.

Adding some kind of configuration or env var to change the browser used would be helpful. For example, on mac, using `open` instead will open the URL with whatever default application you use to handle URLs. On linux, defaulting to [`xdg-open`](https://linux.die.net/man/1/xdg-open) would probably be a good default too.

**Comment by alok** [comment]
#34 addresses some of this.

**Comment by ergl** [comment]
Fixed by #34
