### ISSUE TITLE
Void doesn't save .db if you crash?

### ISSUE THREAD

**Issue by amj** [void-rs/void#53]
I had void up in a terminal, and ran my laptop out of batteries.  many days of void items disappeared into the, well, into the void.  Could void save intermittently?

**Comment by spacejam** [comment]
Hey @amj that sounds incredibly frustrating. I've just added https://github.com/void-rs/void/pull/55 and I'll cut a release shortly that includes an auto-save feature that I believe will prevent such huge losses over time.

**Comment by amj** [comment]
Awesome, thanks for listening to my suggestion!  really excited to keep using this :)
